### ISSUE TITLE
ntasks and jobid

### ISSUE THREAD

**Issue by mikkoku** [kleinhenz/SlurmClusterManager.jl#1]
Using the package was very smooth. When reading the code to understand what it does I noticed some things.

```ntasks``` and ```jobid``` are overwritten on lines 39 and 40.

Is it intentional that ```jobid``` is not used for anything?

**Comment by kleinhenz** [comment]
thanks! good catch, I think that was just an oversight on my part. Closed in f1673b151a3abef19e83fb252301af3c2f5a933d.
