### ISSUE TITLE
n allocated processes, and n+1 spawned in julia

### ISSUE THREAD

**Issue by matthiasbe** [kleinhenz/SlurmClusterManager.jl#3]
If I use the command `sbatch -n 4 script.jl` with the script of your example, I see that there are 4 workers registered, plus 1 master process.

How will these 5 processes be distributed on the 4 allocated resources ? Is the master process sharing a resource with one of the worker processes ?

**Comment by kleinhenz** [comment]
yeah currently the master process shares resources with the 1st worker process. It might be nice to have an option to not do this for cases where you need master to stay responsive. Do you have a case where this causes problems?

**Comment by matthiasbe** [comment]
Ok interesting ! I wanted to know what was happening, in my use case it actually what I would expect.
