### ISSUE TITLE
Shebang pass options in scripts

### ISSUE THREAD

**Issue by Lightup1** [kleinhenz/SlurmClusterManager.jl#9]
In linux system if you want to pass options to julia, for example passing `--project=.` by `#!/usr/bin/env julia --project=.`, you may fail.
It seems better to change it into this one.
```
#!/bin/bash
#=
exec julia --color=yes --startup-file=no "${BASH_SOURCE[0]}" "$@"
=#

@show ARGS  # put any Julia code here
```
which is introduced in [julia documentation](https://docs.julialang.org/en/v1/manual/faq/#How-do-I-pass-options-to-julia-using-#!/usr/bin/env?)

**Comment by kleinhenz** [comment]
is this a suggestion for the example in the README? To me this seems like mostly orthogonal to this package.
